### ISSUE TITLE
 [Model] Medication Category Schema

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.React-Node#111]
As a developer, I want a Medication Category schema, so I create models using this Schema.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] Profile Schema is available.
- [x] Schema defines: 
    - Name of category
    - Default unit (eg. ml, pcs)
    - Default colour of category
    - Default icon of category

### Additional notes
* Think about type and options (eg. minLength, trim) for each field. Feel free to add comments for this issue.
* Think about any other field that might be needed.
* Create a new file in the src/models directory.

**Comment by Urszuja** [comment]
done
