### ISSUE TITLE
[UI] Light and dark theme

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.React-Node#24]
As a user, I want to have the ability to change the theme of the app.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] When the switch available in the navigation bar is clicked, the theme of the app is changed.
- [x] Light theme is available.
- [x] Dark theme is available.

### Additional notes
* Follow the project on the Miro (blue one, but keep in mind, that we may be implementing, dark-theme toggle).
* Use Material UI components.
* Create reusable components if possible.

**Comment by Urszuja** [comment]
done, great success!
