### ISSUE TITLE
[UI] Navigation Bar

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.React-Node#6]
As a user, I want to have a Navigation Bar to easily move around the app.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] A navigation bar is shown at the top of every page.
- [x] It is split into two sections.
  - Left section has buttons 'Daily Drugs', 'Lexicon', 'Calendar' and clickable Logo.
  - Right section has the 'Settings' button, dark-mode toggle and clickable Log Out button (with icon only).

### Additional notes
* Follow the project on the Miro (blue one, but keep in mind, that we may be implementing, dark-theme toggle).
* Use Material UI components.
* Create reusable components if possible.

**Comment by Urszuja** [comment]
![image](https://user-images.githubusercontent.com/43433352/149223774-a3bd6cab-c335-4b91-9539-4a62478a70a9.png)

I changed the order, I would like to introduce setting icon instead of plain text. 💯 Plain text is hideous 👎
