### ISSUE TITLE
[Navigation] App Routing

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.React-Node#7]
As a developer, I want to have one place with all the routes so I can easily extend the application with new pages.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] user hub path is available.
- [x] calendar path is available.
- [x] login path is available.
- [x] register path is available.
- [x] Welcome Screen is shown at the base path.
- [x] daily drugs path is available.
- [x] lexicon path is available.

### Additional notes
* Keep paths in constants.

**Comment by Urszuja** [comment]
ready
